export enum profileTypes {
  PROFILE_ACCOUNT = "PROFILE_ACCOUNT",
  PROFILE_ACCOUNT_SUCCESS = "PROFILE_ACCOUNT_SUCCESS",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS",
}
